#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  2 21:07:25 2016

@author: carissagadson
"""
## step 3 of challenge

import requests, json

## construct HTTP POST request
url3 = 'http://challenge.code2040.org/api/haystack'

headers1 = {'Content-Type': 'application/json'}

params1 = {'token': 'acfd4bea2a23e4735a50a5318245b87d'}

resp1 = requests.post(url3, data=json.dumps(params1), headers=headers1)

## turn resp1 from bytes to string
nd_dict_str = str(resp1.content,'utf-8')
## turn string into useable dictionary
nd_dict = json.loads(nd_dict_str)
## initialize haystack as list
haystack = nd_dict["haystack"]
## initalize needle as string to search for
needle = nd_dict["needle"]

## find index of needle in haystack
index = haystack.index(needle)

## construct second HTTP POST request with solution
url3_1 = 'http://challenge.code2040.org/api/haystack/validate'

headers2 = {'Content-Type': 'application/json'}

params2 = {'token': 'acfd4bea2a23e4735a50a5318245b87d', 'needle': index}

resp2 = requests.post(url3_1, data=json.dumps(params2), headers=headers2)

## print status
#print(resp2.status_code, resp2.reason)
