#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov  2 15:45:24 2016

@author: carissagadson
"""
## step 2 of challenge

import requests, json

## construct HTTP POST request
url2 = 'http://challenge.code2040.org/api/reverse'

headers1 = {'Content-Type': 'application/json'}

params1 = {'token': 'acfd4bea2a23e4735a50a5318245b87d'}

resp1 = requests.post(url2, data=json.dumps(params1), headers=headers1)

## convert response from bytes to string
string = str(resp1.content,'utf-8')

## initialize list that will hold each char of string
to_be_reversed = []
## construct list of chars from string
for position in range(len(string)):
    to_be_reversed.append(string[position])
## reverse the list
reversed_list = to_be_reversed[::-1]
## turn the reversed list back into a string
reversed_str = ''.join(reversed_list)

## construct second HTTP POST request with solution
url2_1 = 'http://challenge.code2040.org/api/reverse/validate'

headers2 = {'Content-Type': 'application/json'}

params2 = {'token': 'acfd4bea2a23e4735a50a5318245b87d', 'string': reversed_str}

resp2 = requests.post(url2_1, data=json.dumps(params2), headers=headers2)

## print status
#print(resp2.status_code, resp2.reason)



